-- Schema v1: numeric usage only. Apply only to an empty database.
BEGIN IMMEDIATE;
CREATE TABLE usage_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  "event_uuid" TEXT NOT NULL UNIQUE,
  "created_at" TEXT,
  "created_epoch" REAL,
  "started_at" TEXT,
  "started_ns" INTEGER NOT NULL,
  "finished_at" TEXT,
  "client_source" TEXT,
  "client_instance_id" TEXT,
  "conversation_id" TEXT,
  "chat_id" TEXT,
  "session_id" TEXT,
  "message_id" TEXT,
  "parent_session_id" TEXT,
  "project_id" TEXT,
  "client_request_id" TEXT,
  "upstream_request_id" TEXT,
  "request_kind" TEXT,
  "agent_id" TEXT,
  "integration_profile_id" TEXT,
  "provider_id" TEXT,
  "requested_model" TEXT,
  "response_model" TEXT,
  "deployment_id" TEXT,
  "endpoint" TEXT,
  "is_stream" INTEGER,
  "message_count" INTEGER,
  "prompt_tokens" INTEGER,
  "completion_tokens" INTEGER,
  "total_tokens" INTEGER,
  "usage_status" TEXT,
  "usage_source" TEXT,
  "usage_accuracy" TEXT,
  "total_tokens_source" TEXT,
  "usage_details" TEXT,
  "usage_observations" TEXT,
  "flags" TEXT,
  "context_limit" INTEGER,
  "output_limit" INTEGER,
  "detected_context_limit" INTEGER,
  "context_limit_source" TEXT,
  "context_limit_status" TEXT,
  "registry_revision" TEXT,
  "request_status" TEXT,
  "http_status" INTEGER,
  "finish_reason" TEXT,
  "duration_ms" REAL,
  "retry_count" INTEGER,
  "fallback_count" INTEGER,
  "cache_hit" INTEGER,
  "gateway_version" TEXT
);
CREATE INDEX idx_events_time ON usage_events(started_ns DESC, id DESC);
CREATE INDEX idx_events_chat ON usage_events(client_source,client_instance_id,conversation_id,started_ns DESC,id DESC);
CREATE INDEX idx_events_model ON usage_events(integration_profile_id,provider_id,requested_model,id DESC);
PRAGMA user_version=1;
COMMIT;
